version: "3"
services:
  client:
    container_name: movietowatch-client-container
    build:
      context: ./client
    ports:
      - 4200:80

  api:
    container_name: movietowatch-api-container
    build:
      context: ./api
    links:
      - database
    ports:
      - 3000:3000

  database:
    container_name: movietowatch-db-container
    image: mongo:6
    ports:
      - 27018:27017

  proxy:
    container_name: movietowatch-proxy-container
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - api
    links:
      - api
      - client
    restart: always
